name: ncr_hachathon
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  local_auth: ^0.4.0+1
  font_awesome_flutter: ^8.4.0
  google_maps_flutter: ^0.4.0
  flutter_auth_buttons: ^0.3.1
  flutter_signin_button: ^0.2.8
  geolocator: ^3.0.1
  carousel_slider: ^1.3.0
  flutter_google_places: ^0.2.1
  cached_network_image: ^0.7.0
  cloud_firestore: ^0.9.7+2
  circular_check_box: ^0.0.2
  flutter_range_slider: ^1.1.0
  flutter_xlider: ^2.2.1
  datetime_picker_formfield: ^0.1.8
  image_picker: ^0.5.0+9
  firebase_ml_vision: ^0.6.0+2
  unicorndial: ^1.1.5
  flushbar: ^1.3.1
  flutter_nfc_reader: ^0.0.23
  firebase_messaging: ^4.0.0+1
  qr_flutter: ^1.1.1
  numberpicker: ^1.0.0
  smooth_star_rating: ^1.0.2
  percent_indicator: ^1.0.14


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/food1.jpg
    - assets/food2.jpg
    - assets/food3.jpg
    - assets/onions.jpg
    - assets/pizza_base.jpg
    - assets/potatoes.jpg
    - assets/tomatoes.jpg
    - assets/promo1.jpg
    - assets/promo2.jpg
    - assets/promo3.jpg
    - assets/background.jpg
    - assets/user.jpg

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
